zsh: git_flip_commits: abort if not a git repo

diff --git a/zsh/func/git_flip_commits b/zsh/func/git_flip_commits
--- a/zsh/func/git_flip_commits
+++ b/zsh/func/git_flip_commits
@@ -3,6 +3,11 @@
 # Flip the order of the top 2 commits.
 git_flip_commits()
 {
+	if ! git_contents; then
+		echo "not a git repo; aborting"
+		return 1
+	fi
+
 	# If the tree is dirty, abort.
 	if [[ -n "$(git diff)" || -n "$(git diff --cached)" ]]; then
 		echo "dirty tree; aborting"
