zsh: univ_open: error messages at bottom, not top

diff --git a/zsh/func/univ_open b/zsh/func/univ_open
--- a/zsh/func/univ_open
+++ b/zsh/func/univ_open
@@ -64,9 +64,9 @@ univ_open() {
         if [[ $# -eq 1 ]]; then
             cd $@ && ${=ls}
         else
-            echo "  univ_open: argument(s) ignored: \`${=@[2,-1]}\`"
-            echo "  univ_open: cd-ing to \`$1'\n"
             cd $1 && ${=ls}
+            echo "\n  univ_open: argument(s) ignored: \`${=@[2,-1]}\`"
+            echo "  univ_open: went to \`$1'\n"
         fi
     elif [[ ! -e $@ ]]; then
         [[ $# -gt 1 ]] && head=$1:h || head=$@:h
@@ -75,12 +75,12 @@ univ_open() {
         # find the closest valid directory, just in case the user gave a
         # butchered-up path
         while [[ ! -d $head ]]; do head=$head:h; done
-        echo "  univ_open: path \`$@' does not exist"
-        [[ $head == "." ]] && echo "  univ_open: staying in same directory\n" || echo "  relocating to nearest parent directory \`$head'\n"
         cd $head && ${=ls}
+        echo "\n  univ_open: path \`$@' does not exist"
+        [[ $head == "." ]] && echo "  univ_open: stayed in same directory\n" || echo "  univ_open: relocated to nearest parent directory \`$head'\n"
     else
         # possible error -- should re-program the above if this ever happens,
         # but, it seems unlikely
-        echo "  univ_open: error -- exiting peacefully"
+        echo "\n  univ_open: error -- exiting peacefully"
     fi
 }
