zsh: univ_open and dir_info
- new, more informative, modular function dir_info to replace the various
"intelligent" aliases to the `ls` command.
- univ_open now uses dir_info

diff --git a/zsh/func/univ_open b/zsh/func/univ_open
--- a/zsh/func/univ_open
+++ b/zsh/func/univ_open
@@ -9,19 +9,22 @@
 # passing flags is that the either the first word or last word must be a valid
 # filename.
 
+# univ_open requires the custom shell function dir_info() (`ls` with saner
+# default args) to work properly
+
 univ_open() {
-    ls="ls -Ahs --color=auto"
     if [[ -z $@ ]]; then
         # if we do not provide any arguments, go to the home directory
-        cd && ${=ls} # ("cd" w/o any arguments goes to the home directory)
+        cd && dir_info # ("cd" w/o any arguments goes to the home directory)
     elif [[ -f $1 || -f ${=@[-1]} ]]; then
-        # if we're here, it means that the user either (1) provided a single
-        # valid file name, or (2) provided a single valid file name PLUS any
-        # number of additional arguments; use of the $@ variable ensures that
-        # we preserve all the arguments the user passed to us
+        # if we're here, it means that the user either (1) provided a single valid file name, or (2) a number of
+        # commandline arguments PLUS a single valid file name; use of the $@ variable ensures that we preserve all the
+        # arguments the user passed to us
 
-        # $1 is the first arg; ${=@[-1]} is the last arg
-        # use && and || for simple ternary operation
+        # $1 is the first arg; ${=@[-1]} is the last arg (i.e., if user passes "-o -m FILE" to us, then obviously the
+        # last arg is the filename
+        #
+        # we use && and || for simple ternary operation (like ? and : in C)
         [[ -f $1 ]] && file=$1 || file=${=@[-1]}
         case $file:e:l in
             (doc|odf|odt|rtf)
@@ -58,18 +61,30 @@ univ_open() {
                 wine $@ &>/dev/null & disown
             ;;
             *)
-                vim $@
+                # if it's a file of size 0 or a text file, then open with vim;
+                # otherwise, tell user that this is an unknown binary format
+                # and do nothing
+
+                if [[ `ls -s $1 | cut -d " " -f1` == "0" || `file -bizL $1 | cut -d/ -f1` == "text" ]]; then
+                    vim $@
+                else
+                    echo "univ_open: unknown binary format detected\nuniv_open: operation aborted (no change)"
+                fi
             ;;
         esac
     elif [[ -d $1 ]]; then
         # if the first argument is a valid directory, just cd into it -- ignore
-        # any trailing arguments
+        # any trailing arguments (in zsh, '#' is the same as ARGC, and denotes the number of arguments passed to the
+        # script (so '$#' is the same as $ARGC)
         if [[ $# -eq 1 ]]; then
-            cd $@ && ${=ls}
+            cd $@ && dir_info
         else
-            cd $1 && ${=ls}
-            echo "\n  univ_open: argument(s) ignored: \`${=@[2,-1]}\`"
-            echo "  univ_open: went to \`$1'\n"
+            # if the first argument was a valid directory, but there was more than 1 argument, then we ignore these
+            # trailing args but still cd into the first given directory
+            cd $1 && dir_info
+            # i.e., show arguments 2 ... all the way to the last one (last one has an index of -1 argument array)
+            echo "\nuniv_open: argument(s) ignored: \`${=@[2,-1]}\`"
+            echo "univ_open: went to \`$1'\n"
         fi
     elif [[ ! -e $@ ]]; then
         [[ $# -gt 1 ]] && head=$1:h || head=$@:h
@@ -78,12 +93,12 @@ univ_open() {
         # find the closest valid directory, just in case the user gave a
         # butchered-up path
         while [[ ! -d $head ]]; do head=$head:h; done
-        cd $head && ${=ls}
-        echo "\n  univ_open: path \`$@' does not exist"
-        [[ $head == "." ]] && echo "  univ_open: stayed in same directory\n" || echo "  univ_open: relocated to nearest parent directory \`$head'\n"
+        cd $head && dir_info
+        echo "\nuniv_open: path \`$@' does not exist"
+        [[ $head == "." ]] && echo "univ_open: stayed in same directory\n" || echo "univ_open: relocated to nearest parent directory \`$head'\n"
     else
         # possible error -- should re-program the above if this ever happens,
         # but, it seems unlikely
-        echo "\n  univ_open: error -- exiting peacefully"
+        echo "\nuniv_open: error -- exiting peacefully"
     fi
 }
