zsh: univ_open: much better error handling and also support for passing args to valid files

diff --git a/zsh/func/univ_open b/zsh/func/univ_open
--- a/zsh/func/univ_open
+++ b/zsh/func/univ_open
@@ -1,24 +1,26 @@
-# open up directories and files intelligently
+#!/bin/zsh
+
+# univ_open() is intended to be used to pass either a SINGLE valid FILE or
+# DIRECTORY. For illustrative purposes, we assume "d" to be aliased to
+# univ_open() in ~/.zshrc. If optional flags are desired, then either prepend
+# or append them appropriately. E.g., if you have jpg's to be opened by eog,
+# then doing "d -f file.jpg" or "d file.jpg -f" will be the same as "eog -f
+# file.jpg" or "eog file.jpg -f", respectively. The only requirement when
+# passing flags is that the either the first word or last word must be a valid
+# filename.
 
 univ_open() {
     ls="ls -Ahs --color=auto"
-    if [[ -z $@ ]]; then
-        # if we do not provide any arguments, go to the home directory
-        cd && ${=ls}
-    elif [[ ! -e $@ ]]; then
-        # go to the nearest valid parent directory if file does not exist; we
-        # use a while loop to find the closest valid directory, just in case
-        # the user gave a butchered-up path
-        d=$@:h
-        while [[ ! -d $d ]]
-        do
-            d=$d:h
-        done
-        cd $d && ${=ls}
-    elif [[ -d $@ ]]; then
-        cd $@ && ${=ls}
-    else
-        case $@:e:l in
+    if [[ -f $1 || -f ${=@[-1]} ]]; then
+        # if we're here, it means that the user either (1) provided a single
+        # valid file name, or (2) provided a single valid file name PLUS any
+        # number of additional arguments; use of the $@ variable ensures that
+        # we preserve all the arguments the user passed to us
+
+        # $1 is the first arg; ${=@[-1]} is the last arg
+        # use && and || for simple ternary operation
+        [[ -f $1 ]] && file=$1 || file=${=@[-1]}
+        case $file:e:l in
             (doc|odf|odt|rtf)
                 soffice -writer $@ &>/dev/null & disown
             ;;
@@ -44,8 +46,35 @@ univ_open() {
                 smplayer $@ &>/dev/null & disown
             ;;
             *)
-            vim $@
+                vim $@
             ;;
         esac
+    elif [[ -d $1 ]]; then
+        # if the first argument is a valid directory, just cd into it -- ignore
+        # any trailing arguments
+        if [[ $# -eq 1 ]]; then
+            cd $@ && ${=ls}
+        else
+            echo "  argument(s) ignored: \`${=@[2,-1]}\`"
+            echo "  cd-ing to \`$1'\n"
+            cd $1 && ${=ls}
+        fi
+    elif [[ ! -e $@ ]]; then
+        [[ $# -gt 1 ]] && head=$1:h || head=$@:h
+        # if we're given just 1 argument, and that argument does not exist,
+        # then go to the nearest valid parent directory; we use a while loop to
+        # find the closest valid directory, just in case the user gave a
+        # butchered-up path
+        while [[ ! -d $head ]]; do head=$head:h; done
+        echo "  path \`$@' does not exist"
+        [[ $head == "." ]] && echo "  staying in same directory\n" || echo "  relocating to nearest parent directory \`$head'\n"
+        cd $head && ${=ls}
+    elif [[ -z $@ ]]; then
+        # if we do not provide any arguments, go to the home directory
+        cd && ${=ls} # ("cd" w/o any arguments goes to the home directory)
+    else
+        # possible error -- should re-program the above if this ever happens,
+        # but, it seems unlikely
+        echo "univ_open(): error -- exiting peacefully"
     fi
 }
