zsh: univ_open: error messages did not identify their source

diff --git a/zsh/func/univ_open b/zsh/func/univ_open
--- a/zsh/func/univ_open
+++ b/zsh/func/univ_open
@@ -58,8 +58,8 @@ univ_open() {
         if [[ $# -eq 1 ]]; then
             cd $@ && ${=ls}
         else
-            echo "  argument(s) ignored: \`${=@[2,-1]}\`"
-            echo "  cd-ing to \`$1'\n"
+            echo "  univ_open: argument(s) ignored: \`${=@[2,-1]}\`"
+            echo "  univ_open: cd-ing to \`$1'\n"
             cd $1 && ${=ls}
         fi
     elif [[ ! -e $@ ]]; then
@@ -69,12 +69,12 @@ univ_open() {
         # find the closest valid directory, just in case the user gave a
         # butchered-up path
         while [[ ! -d $head ]]; do head=$head:h; done
-        echo "  path \`$@' does not exist"
-        [[ $head == "." ]] && echo "  staying in same directory\n" || echo "  relocating to nearest parent directory \`$head'\n"
+        echo "  univ_open: path \`$@' does not exist"
+        [[ $head == "." ]] && echo "  univ_open: staying in same directory\n" || echo "  relocating to nearest parent directory \`$head'\n"
         cd $head && ${=ls}
     else
         # possible error -- should re-program the above if this ever happens,
         # but, it seems unlikely
-        echo "univ_open(): error -- exiting peacefully"
+        echo "  univ_open: error -- exiting peacefully"
     fi
 }
